import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { 
  Chart as ChartJS,
  LinearScale,
  PointElement,
  Tooltip,
  Legend
} from 'chart.js'
import { Bubble } from 'react-chartjs-2'
import React, { useState, useEffect } from 'react'
import { faker } from '@faker-js/faker';
import Link from 'next/link'

ChartJS.register(
    LinearScale,
    PointElement,
    Tooltip,
    Legend
)

export default function Home() {

  const [chartData, setChartData] = useState({
    datasets: []
  })

  const [chartOptions, setChartOptions] = useState({})

    useEffect(() => {
        setChartData({
            datasets: [
                {
                    label: 'Red dataset',
                    data: [
                        {x: -10, y: 10, r: 40},
                        {x: 50, y: 0, r: 20},
                        {x: 3, y: 30, r: 10},
                    ],
                    backgroundColor: 'rgba(255, 99, 132, 0.5)',
                },
                {
                    label: 'Blue dataset',
                    data: [
                        {x: -20, y: 60, r: 20},
                        {x: 10, y: 40, r: 50},
                        {x: 30, y: 20, r: 80},
                    ],
                    backgroundColor: 'rgba(53, 162, 235, 0.5)',
                },
            ],
        })
        setChartOptions({
            scales: {
                y: {
                    beginAtZero: true,
                },
            },
        })
    }, [])

    return (
        <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <Link href="/">
            Go to Home Page
            </Link>
            <div style={{width: "60%"}}>
                <Bubble options={chartOptions} data={chartData} />
            </div>
        </main>

        </div>
    )
}
